- |
  Я бы сказал, но промолчу
  Выражение на несколько строк, длинных, очень длинных и ну весьма просто длиннючих.
  А следующая строка - уже покороче...

- |
  Ещё одно выражение
  Пустое, но из трёх строк...
